extern u64 minecraftDiamondSwordBladeDL_diamond_sword_ci4[];
extern u64 minecraftDiamondSwordBladeDL_diamond_sword_pal_rgba16[];
extern Vtx minecraftDiamondSwordBladeDL_minecraftDiamondSwordBladeDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx minecraftDiamondSwordBladeDL_minecraftDiamondSwordBladeDL_mesh_layer_Opaque_vtx_0[498];
extern Gfx minecraftDiamondSwordBladeDL_minecraftDiamondSwordBladeDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_minecraftDiamondSwordBladeDL_diamond_sword_layerOpaque[];
extern Gfx minecraftDiamondSwordBladeDL[];
